force-app/main/default/objects/BMCServiceDesk__Incident__c/BMCServiceDesk__Incident__c.object-meta.xml
<CustomObject>
    <customHelpPage>BMCServiceDesk__StdFormHelpIncident</customHelpPage>
    <description>This object allows you to store data for incidents.</description>
    <label>Incident</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Incidents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/BMCServiceDesk__Incident__c/fields/Subcategory_1__c.field-meta.xml
<CustomField>
    <fullName>Subcategory_1__c</fullName>
    <label>Subcategory</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Subcategory__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Assessment</fullName>
            </value>
            <value>
                <fullName>Create Application / Add Documents</fullName>
            </value>
            <value>
                <fullName>Outcome Submission</fullName>
            </value>
            <value>
                <fullName>Submit Additional Information</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BMCServiceDesk__Incident__c/fields/Subcategory__c.field-meta.xml
<CustomField>
    <fullName>Subcategory__c</fullName>
    <label>Type of MyPortalt Issue</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type_of_Fault__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Chartered</fullName>
            </value>
            <value>
                <fullName>eMembership</fullName>
            </value>
            <value>
                <fullName>eStage1</fullName>
            </value>
            <value>
                <fullName>National Registration</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BMCServiceDesk__Incident__c/fields/Type_of_Fault__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Fault__c</fullName>
    <label>Type of Fault</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MyPortal</fullName>
            </value>
            <value>
                <fullName>Cvent</fullName>
            </value>
            <value>
                <fullName>Salesforce</fullName>
            </value>
            <value>
                <fullName>Confluence</fullName>
            </value>
            <value>
                <fullName>EA Corporate Website</fullName>
            </value>
            <value>
                <fullName>Mitel Software</fullName>
            </value>
            <value>
                <fullName>Oracle</fullName>
            </value>
            <value>
                <fullName>Outlook 365</fullName>
            </value>
            <value>
                <fullName>Webex</fullName>
            </value>
            <value>
                <fullName>Hardware</fullName>
            </value>
            <value>
                <fullName>Printer</fullName>
            </value>
            <value>
                <fullName>AV/VC Equipment</fullName>
            </value>
            <value>
                <fullName>VPN (Remote Access)</fullName>
            </value>
            <value>
                <fullName>Security</fullName>
            </value>
            <value>
                <fullName>Wireless</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BMCServiceDesk__Incident__c/fields/Type_of_ticket__c.field-meta.xml
<CustomField>
    <fullName>Type_of_ticket__c</fullName>
    <label>Type of ticket</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Is something broken (used to work but no longer does)</fullName>
                <label>Is something broken (e.g. did work but no longer does)</label>
            </value>
            <value>
                <fullName>Do you Require something (Access, new hardware, new starter, departures)</fullName>
                <label>Do you Require something (e.g. access, hardware)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/NewIncidentCreateHandler.cls
public with sharing class NewIncidentCreateHandler {
    public NewIncidentCreateHandler() {

    }

    public static void HandleCreate(List<BMCServiceDesk__Incident__c>newInc){

        System.debug('In HandleCreate');
        System.debug('newInc >>>' + newInc);
        Boolean isSR = false;
        String strIncCat = '';
        for(BMCServiceDesk__Incident__c inc: newInc){
            System.debug('Type_of_ticket__c >>>' + inc.Type_of_ticket__c);
            if((inc.Type_of_ticket__c).contains('Is something broken')){
                isSR = false;
                System.debug('type of Fault >>' + inc.Type_of_Fault__c);
                if(inc.Type_of_Fault__c == 'MyPortal'){
                    strIncCat = inc.Subcategory__c +' '+'-'+' '+inc.Subcategory_1__c;    
                }
                else if(inc.Type_of_Fault__c == 'Cvent' || inc.Type_of_Fault__c != 'Salesforce'){
                    strIncCat = 'Application - '+ (inc.Type_of_Fault__c);
                }

                System.debug('strIncCat >>' + strIncCat);
            }
            else if((inc.Type_of_ticket__c).contains('Do you Require something')){
                isSR = true;
            }
        }

    }
}